server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Damsak/microservices-config-store2-damsak
          default-label: main
          search-paths:
            - 'service-config/*service'
