server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Damsak/spring-cloud-config-store-damsak
          default-label: main
          search-paths:
            - '*service'
